name: CI

on:
  push:
    branches: [main]

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: du
      - run: dnf install -y curl dnf-utils rpm-build
      - run: curl -o a.rpm https://kojipkgs.fedoraproject.org//packages/qt6-qtwebengine/6.6.1/1.fc40/src/qt6-qtwebengine-6.6.1-1.fc40.src.rpm
      - run: dnf builddep -y --srpm a.rpm
      - run: du
      - run: rpm -ivh a.rpm
      - uses: actions/checkout@v4
      - run: pushd /github/home/rpmbuild/SPEC && rpmbuild -bb qt6-qtwebengine.spec && popd
      - run: du
