name: CI

on:
  push:
    paths-ignore:
      - README.md
    tags:
      - Qt6WE-OT-SVG*

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: df
      - run: dnf install -y dnf-utils rpm-build
      - run: curl -o a.rpm https://kojipkgs.fedoraproject.org//packages/qt6-qtwebengine/6.6.1/1.fc40/src/qt6-qtwebengine-6.6.1-1.fc40.src.rpm
      - run: dnf builddep -y --srpm a.rpm
      - run: df
      - run: rpm -ivh a.rpm
      - uses: actions/checkout@v4
      - run: patch ~/rpmbuild/SPECS/qt6-qtwebengine.spec qt6-qtwebengine.spec.diff
      - run: cp skia-m112-OT-SVG-hook.patch ~/rpmbuild/SOURCES/
      - run: dnf install -y wget
      - run: wget https://download.qt.io/development_releases/qt/6.7/6.7.0-beta1/submodules/qtwebengine-everywhere-src-6.7.0-beta1.tar.xz
      - run: cp ~/rpmbuild/SOURCES/*.sh ~/rpmbuild/SOURCES/*.py .
      - run: perl -pi -e "s(.+openh264.+)()" clean_qtwebengine.sh
      - run: ./clean_qtwebengine.sh 6.7.0-beta1
      - run: cp 000*.patch ~/rpmbuild/SOURCES/
      - run: mv qtwebengine-everywhere-src-6.7.0-beta1-clean.tar.xz ~/rpmbuild/SOURCES/
      - run: pushd ~/rpmbuild/SPECS && rpmbuild -bb --noclean qt6-qtwebengine.spec && popd
      - run: find ~/rpmbuild/BUILD -type f -name "platform_jumbo_29.cc" -print -exec cp {} ~/rpmbuild/RPMS \;
      - run: df
      - run: rm -f ~/rpmbuild/RPMS/x86_64/*debug*
      - run: cp -r ~/rpmbuild/RPMS .
      - uses: actions/upload-artifact@v3
        with:
          name: rpms
          path: RPMS
      - run: zip -r9X rpms.zip RPMS
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/Qt6WE-OT-SVG')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/Qt6WE-OT-SVG')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rpms.zip
          asset_name: rpms.zip
          asset_content_type: application/zip
